CC = gcc
LIB = myftp.c

all: server client

server: myftpserver.c
	${CC} -o myftpserver myftpserver.c ${LIB} -lsocket -lnsl

client: myftpclient.c
	${CC} -o myftpclient myftpclient.c ${LIB} -lsocket -lnsl


clean:
	rm myftpserver
	rm myftpclient
